Cinema/Cinema.WEB/Controllers/MovieController.cs
using AutoMapper;
using Cinema.WEB.Helpers;
using Cinema.WEB.Models.MovieModels.MovieVms;
using Cinema.WEB.Models.MovieModels;
using Microsoft.AspNetCore.Mvc;
using Cinema.WEB.Services.IServices;
using Cinema.WEB.Models.MovieModels.MovieDtos;

namespace Cinema.WEB.Controllers
{
    public class MovieController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public MovieController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        //GET: MovieController/MovieIndex
        public async Task<IActionResult> MovieIndex(
            bool sort,
            string? titleFilter = null,
            string? genreFilter = null,
            string? directorFilter = null,
            string? search = null,
            int page = 1, int pageSize = 20)
        {
            var request = new MoviesFilterRequest(search, titleFilter, directorFilter, genreFilter, sort, pageSize, page);
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var pageResponse = await _unitOfWork.Movies.GetAllMoviesAsync(token!, request);
            if (pageResponse is not null)
            {
                return View(pageResponse);
            }

            return View(new MovieFilteredResponse());
        }

        //GET: MovieController/MovieDetails/5
        public async Task<IActionResult> MovieDetails(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var movieDto = await _unitOfWork.Movies.GetMovieAsync(id, token!);
            if (movieDto is null)
            {
                TempData["error"] = "Oops! Неудалось найти фильм.";
                return RedirectToAction(nameof(MovieIndex));
            }

            var movieVm = _mapper.Map<MovieVm>(movieDto);   
            return View(movieVm);
        }

        //GET: MovieController/MovieCreate
        public async Task<IActionResult> MovieCreate()
        {
            var movieVm = new MovieCreateVm();
            var token = HttpContext.Session.GetString(SD.SessionToken);
            movieVm.ActorList = await _unitOfWork.Actors.GetSelectListOfActorsAsync(token!, movieVm.Movie.Actors);
            movieVm.DirectorList = await _unitOfWork.Directors.GetSelectListOfDirectorsAsync(token!, movieVm.Movie.Directors);
            movieVm.ScreenwriterList = await _unitOfWork.Screenwriters.GetSelectListOfScreenwritersAsync(
                token!, movieVm.Movie.Screenwriters);
            movieVm.GenreList = await _unitOfWork.Genres.GetSelectListOfGenresAsync(token!);
            return View(movieVm);
        }

        // POST: MovieController/MovieCreate
        [HttpPost]
        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]  
        public async Task<IActionResult> MovieCreate(MovieCreateVm movieVm)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            if (ModelState.IsValid)
            {
                movieVm.Movie.ImageUrl = await _unitOfWork.Images.SaveImageAsync(movieVm.ImageFile, movieVm.Movie.ImageUrl, @"images\movies");
                movieVm.Movie.VideoUrl = await _unitOfWork.Videos.SaveVideoAsync(movieVm.VideoFile, movieVm.Movie.VideoUrl, @"videos\movies");
                var response = await _unitOfWork.Movies.CreateMovieAsync(movieVm.Movie, token!);
                if (response.IsSuccess)
                {
                    TempData["success"] = "Информация успешно добавлена!";
                    return RedirectToAction(nameof(MovieIndex));
                }

                _unitOfWork.Images.DeleteImage(movieVm.Movie.ImageUrl);
                _unitOfWork.Videos.DeleteVideo(movieVm.Movie.VideoUrl);
                movieVm.Movie.ImageUrl = null;
                movieVm.Movie.VideoUrl = null;
                movieVm.ActorList = await _unitOfWork.Actors.GetSelectListOfActorsAsync(token!, movieVm.Movie.Actors);
                movieVm.DirectorList = await _unitOfWork.Directors.GetSelectListOfDirectorsAsync(token!, movieVm.Movie.Directors);
                movieVm.ScreenwriterList = await _unitOfWork.Screenwriters.GetSelectListOfScreenwritersAsync(
                    token!, movieVm.Movie.Screenwriters);
                movieVm.GenreList = await _unitOfWork.Genres.GetSelectListOfGenresAsync(token!);
                if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    TempData["error"] = string.Join("\n", response.ErrorMessage);
                    return View(movieVm);
                }
            }

            TempData["error"] = "Oops! Не удалось добавить информацию.";
            return View(movieVm);
        }

        //GET: MovieController/MovieUpdate/1
        public async Task<IActionResult> MovieUpdate(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var movieDto = await _unitOfWork.Movies.GetMovieAsync(id, token!);
            var movieVm = new MovieUpdateVm
            {
                Movie = _mapper.Map<MovieUpdateDto>(movieDto)
            };

            if (movieVm.Movie is null)
            {
                return RedirectToAction(nameof(MovieIndex));
            }

            movieVm.ActorList = await _unitOfWork.Actors.GetSelectListOfActorsAsync(token!, movieVm.Movie.Actors);
            movieVm.DirectorList = await _unitOfWork.Directors.GetSelectListOfDirectorsAsync(token!, movieVm.Movie.Directors);
            movieVm.ScreenwriterList = await _unitOfWork.Screenwriters.GetSelectListOfScreenwritersAsync(
                token!, movieVm.Movie.Screenwriters);
            movieVm.GenreList = await _unitOfWork.Genres.GetSelectListOfGenresAsync(token!);
            return View(movieVm);
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MovieUpdate(MovieUpdateVm movieVm)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            if (ModelState.IsValid)
            {
                var oldImgPath = movieVm.Movie.ImageUrl;
                var oldVideoPath = movieVm.Movie.VideoUrl;
                movieVm.Movie.ImageUrl = await _unitOfWork.Images.SaveImageAsync(movieVm.ImageFile, movieVm.Movie.ImageUrl, @"images\movies");
                movieVm.Movie.VideoUrl = await _unitOfWork.Videos.SaveVideoAsync(movieVm.VideoFile, movieVm.Movie.VideoUrl, @"videos\movies");
                var response = await _unitOfWork.Movies.UpdateMovieAsync(movieVm.Movie, token!);
                if (response.IsSuccess)
                {
                    TempData["success"] = "Информация успешно обновлена!";
                    _unitOfWork.Images.DeleteImage(oldImgPath);
                    _unitOfWork.Videos.DeleteVideo(oldVideoPath);
                    return RedirectToAction(nameof(MovieIndex));
                }

                _unitOfWork.Images.DeleteImage(movieVm.Movie.ImageUrl);
                _unitOfWork.Videos.DeleteVideo(movieVm.Movie.VideoUrl);
                movieVm.Movie.ImageUrl = oldImgPath;
                movieVm.Movie.VideoUrl = oldVideoPath;
                movieVm.ActorList = await _unitOfWork.Actors.GetSelectListOfActorsAsync(token!, movieVm.Movie.Actors);
                movieVm.DirectorList = await _unitOfWork.Directors.GetSelectListOfDirectorsAsync(token!, movieVm.Movie.Directors);
                movieVm.ScreenwriterList = await _unitOfWork.Screenwriters.GetSelectListOfScreenwritersAsync(token!, movieVm.Movie.Screenwriters);
                movieVm.GenreList = await _unitOfWork.Genres.GetSelectListOfGenresAsync(token!);
                if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    TempData["error"] = string.Join("\n", response.ErrorMessage);
                    return View(movieVm);
                }
            }

            TempData["error"] = "Oops! Не удалось обновить информацию.";
            return View(movieVm);
        }

        //POST: MovieController/MovieDelete
        public async Task<IActionResult> MovieDelete(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var movieToDelete = await _unitOfWork.Movies.GetMovieAsync(id, token!);
            if (movieToDelete is not null)
            {
                var isSuccess = await _unitOfWork.Movies.DeleteMovieAsync(id, token!);
                if (isSuccess)
                {
                    if (movieToDelete.ImageUrl is not null)
                        _unitOfWork.Images.DeleteImage(movieToDelete.ImageUrl);
                    if (movieToDelete.VideoUrl is not null)
                        _unitOfWork.Videos.DeleteVideo(movieToDelete?.VideoUrl);
                    TempData["success"] = "Информация успешно удалена!";
                    return RedirectToAction(nameof(MovieIndex));
                }
            }

            TempData["error"] = "Oops! Не удалось удалить информация.";
            return RedirectToAction(nameof(MovieIndex));
        }
    }
}

Cinema/Cinema.WEB/Controllers/PersonController.cs
using Cinema.WEB.Helpers;
using Cinema.WEB.Models.PersonModels;
using Cinema.WEB.Models.PersonModels.PersonVms;
using Cinema.WEB.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using System.Net;

namespace Cinema.WEB.Controllers
{
    public class PersonController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;

        public PersonController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        // GET: PersonController
        public async Task<IActionResult> PersonIndex(
            bool sort, string? search = null, int page = 1, int pageSize = 20)
        {
            var request = new PersonsFilterRequest(sort, search, pageSize, page);
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var pageResponse = await _unitOfWork.Persons.GetAllPersonsAsync(token!, request);
            return View(pageResponse);
        }

        // GET: PersonController/Create
        public ActionResult PersonCreate()
        {
            return View(new PersonCreateVm());
        }

        // POST: PersonController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PersonCreate(PersonCreateVm personVm)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                personVm.Person.ImageUrl = await _unitOfWork.Images.SaveImageAsync(personVm.ImageFile, personVm.Person.ImageUrl, @"images\persons");
                var response = await _unitOfWork.Persons.CreatePersonAsync(personVm.Person, token!);
                if (response.IsSuccess)
                {
                    TempData["success"] = "Информация успешно добавлена!";
                    return RedirectToAction(nameof(PersonIndex));
                }

                _unitOfWork.Images.DeleteImage(personVm.Person.ImageUrl);
                personVm.Person.ImageUrl = null; 
                if (response.StatusCode == HttpStatusCode.BadRequest)
                {
                    TempData["error"] = string.Join("\n", response.ErrorMessage);
                    return View(personVm);
                }
            }

            TempData["error"] = "Oops! Неудалось добавить информацию!";
            return View(personVm);
        }

        // GET: PersonController/PersonUpdate/5
        public async Task<IActionResult> PersonUpdate(Guid id)
        {
            if (id != Guid.Empty)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var personUpdateVm = new PersonUpdateVm
                {
                    Person = await _unitOfWork.Persons.GetPersonAsync(id, token!)
                };

                return View(personUpdateVm);
            }

            TempData["error"] = "Oops! Не удаётся получить информацию!";
            return RedirectToAction(nameof(PersonIndex));
        }

        // POST: PersonController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> PersonUpdate(PersonUpdateVm personVm)
        {
            if (ModelState.IsValid)
            {
                var oldImgPath = personVm.Person.ImageUrl;
                personVm.Person.ImageUrl = await _unitOfWork.Images.SaveImageAsync(personVm.ImageFile, personVm.Person.ImageUrl, @"images\persons");
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var response = await _unitOfWork.Persons.UpdatePersonAsync(personVm.Person, token!);
                if (response.IsSuccess)
                {
                    TempData["success"] = "Информация успешно обновлена!";
                    _unitOfWork.Images.DeleteImage(oldImgPath);
                    return RedirectToAction(nameof(PersonIndex));
                }

                _unitOfWork.Images.DeleteImage(personVm.Person.ImageUrl);
                personVm.Person.ImageUrl = oldImgPath;
                if (response.StatusCode == HttpStatusCode.BadRequest)
                {
                    TempData["error"] = string.Join("\n", response.ErrorMessage);
                    return View(personVm);
                }
            }

            TempData["error"] = "Oops! Неудалось обновить информацию!";
            return View(personVm);
        }

        // POST: PersonController/Delete 
        public async Task<IActionResult> PersonDelete(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var personToDelete = await _unitOfWork.Persons.GetPersonAsync(id, token!);
            if (personToDelete is not null)
            {
                var isSuccess = await _unitOfWork.Persons.DeletePersonAsync(personToDelete.Id, token!);
                if (isSuccess)
                {
                    _unitOfWork.Images.DeleteImage(personToDelete.ImageUrl);
                    TempData["success"] = "Информация успешно удалена!";
                    return RedirectToAction(nameof(PersonIndex));
                }
            }

            TempData["error"] = "Oops! Неудалось удалить информация.";
            return RedirectToAction(nameof(PersonIndex));
        }
    }
}

Cinema/Cinema.WEB/Views/Movie/MovieCreate.cshtml
@model Cinema.WEB.Models.MovieModels.MovieVms.MovieCreateVm

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-10 mt-3 mb-3">
            <div class="card shadow">
                <div class="card-body">
                    <form id="myForm" class="col-md-auto" method="post" asp-action="MovieCreate" enctype="multipart/form-data">
                        <div class="p-3 row">

                            <center>
                                <h1>Обновить фильм</h1>
                            </center>

                            <div class="col-12 pb-2">
                                <hr />
                                <div class="col-md-auto">
                                    <select asp-for="Movie.GenreId" class="form-select text-center" asp-items="@Model.GenreList">
                                        <option disabled selected>--Выберите жанр--</option>
                                    </select>
                                    <span asp-validation-for="Movie.GenreId" class="text-danger"></span>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-12 col-md-6">
                                        <label asp-for="Movie.Title" class="control-label m-1"></label>
                                        <input asp-for="Movie.Title" class="form-control" />
                                        <span asp-validation-for="Movie.Title" class="text-danger"></span>
                                    </div>
                                    <div class="col">
                                        <label asp-for="Movie.Country" class="control-label m-1"></label>
                                        <input asp-for="Movie.Country" class="form-control" />
                                        <span asp-validation-for="Movie.Country" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-12 col-md-6">
                                        <label asp-for="Movie.ReleaseYear" class="control-label m-1"></label>
                                        <input asp-for="Movie.ReleaseYear" class="form-control" />
                                        <span asp-validation-for="Movie.ReleaseYear" class="text-danger"></span>
                                    </div>
                                    <div class="col">
                                        <label asp-for="Movie.RuntimeInMinutes" class="control-label m-1"></label>
                                        <input asp-for="Movie.RuntimeInMinutes" class="form-control" />
                                        <span asp-validation-for="Movie.RuntimeInMinutes" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-md-12">
                                        <label asp-for="Movie.ShortDescription" class="control-label m-1"></label>
                                        <textarea asp-for="Movie.ShortDescription" class="form-control"></textarea>
                                        <span asp-validation-for="Movie.ShortDescription" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-md-12">
                                        <label asp-for="Movie.Description" class="control-label m-1"></label>
                                        <textarea asp-for="Movie.Description" class="form-control"></textarea>
                                        <span asp-validation-for="Movie.Description" class="text-danger"></span>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col-12 col-md-6">
                                        <label asp-for="Movie.VideoUrl" class="control-label m-1"></label>
                                        <input asp-for="VideoFile" type="file" class="form-control" />
                                        <span asp-validation-for="VideoFile" class="text-danger"></span>
                                    </div>
                                    <div class="col">
                                        <label asp-for="Movie.ImageUrl" class="control-label m-1"></label>
                                        <input asp-for="ImageFile" type="file" class="form-control" />
                                        <span asp-validation-for="ImageFile" class="text-danger"></span>
                                    </div>
                                </div>

                                <div>
                                    <div class="form-group mt-3">
                                        <label asp-for="Movie.Directors" class="control-label m-1"></label>
                                        <select asp-for="Movie.Directors" asp-items="Model.DirectorList" class="form-control" multiple></select>
                                    </div>

                                    <div class="form-group mt-3">
                                        <label asp-for="Movie.Screenwriters" class="control-label m-1"></label>
                                        <select asp-for="Movie.Screenwriters" asp-items="Model.ScreenwriterList" class="form-control" multiple></select>
                                    </div>

                                    <div class="form-group mt-3">
                                        <label asp-for="Movie.Actors" class="control-label m-1"></label>
                                        <select asp-for="Movie.Actors" asp-items="Model.ActorList" class="form-control" multiple></select>
                                    </div>
                                </div>

                                <div class="row mt-3">
                                    <div class="col">
                                        <button id="submitButton" type="submit" class="btn btn-primary col-12">Добавить</button>
                                    </div>
                                    <div class="col">
                                        <a asp-controller="Movie" asp-action="MovieIndex" class="btn btn-danger col-12">
                                            Назад
                                        </a>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<button id="scroll-to-top-btn" class="btn btn-primary btn-floating"><i class="bi bi-arrow-up-circle"></i></button>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        await Html.RenderPartialAsync("_TextareaScriptPartial");
        await Html.RenderPartialAsync("_MultipleSelectionPartial");
        await Html.RenderPartialAsync("_SaveMessagePartial");
    }
}

Cinema/Cinema.WEB/Views/Movie/MovieIndex.cshtml
@model Cinema.WEB.Models.MovieModels.MovieFilteredResponse

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-10">
            @using (Html.BeginForm("MovieIndex", "Movie", FormMethod.Get))
            {
                <div class="row justify-content-between">
                    <div class="col-md-auto">
                        <p>
                            <a asp-controller="Movie" asp-action="MovieCreate" class="btn btn-success shadow"><i class="bi bi-plus-square"></i></a>
                        </p>
                    </div>

                    <div class="col-md-auto">
                        <div class="d-flex flex-wrap align-items-center">
                            <div class="flex-fill me-2">
                                <p class="shadow">
                                    @Html.TextBox("search", Model.Search, new { @class = "form-control" })
                                </p>
                            </div>
                            <div>
                                <p>
                                    <input type="submit" value="найти" class="btn btn-primary shadow" />
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            }
            <div class="card shadow">
                <div class="card-body">

                    @foreach (var movie in Model.MoviesPage.Items)
                    {
                        <div class="card-body">
                            <div class="row">
                                <a asp-controller="Movie" asp-action="MovieDetails" asp-route-id="@movie.Id" class="col-lg-3 d-flex justify-content-center align-items-center">
                                    @if (!string.IsNullOrEmpty(movie.ImageUrl))
                                    {
                                        <img id="preview" src="@movie.ImageUrl" alt="movie img" class="img-fluid rounded" style="object-fit:cover; height: 100%;">
                                    }
                                    else
                                    {
                                        <img id="preview" src="\images\default_icon.png" class="img-fluid rounded" style="object-fit: contain;">
                                    }
                                </a>
                                <div class="col-lg-9">
                                    <div class="row">
                                        <div class="col-9">
                                            <h4>@movie.Title</h4>
                                        </div>
                                        <div class="col-3 text-end">
                                            <a asp-controller="Movie" asp-action="MovieUpdate" asp-route-id="@movie.Id" class="btn btn-success"><i class="bi bi-pencil-square"></i></a>
                                            <a asp-controller="Person" asp-action="MovieDelete" asp-route-id="@movie.Id" class="btn btn-danger delete-btn"><i class="bi bi-trash"></i></a>
                                        </div>
                                    </div>
                                    <div class="col">
                                        <span><b>Год выпуска:</b></span>
                                        @movie.ReleaseYear
                                    </div>
                                    <div class="col mt-1">
                                        <span><b>Страна:</b></span>
                                        @movie.Country
                                    </div>
                                    <div class="col mt-1">
                                        <span><b>Жанр:</b></span>
                                        @movie.Genre.Name
                                    </div>
                                    <div class="col mt-1">
                                        <span><b>Продолжительность:</b></span>
                                        @movie.RuntimeInMinutes мин.
                                    </div>
                                    <div class="col mt-1">
                                        <span><b>Режиссёр:</b></span>
                                        @string.Join(", ", movie.Directors.Select(d => $"{d.FirstName} {d.LastName}"))
                                    </div>
                                    <div class="col mt-1">
                                        <span><b>Сценарий:</b></span>
                                        @string.Join(", ", movie.Screenwriters.Select(s => $"{s.FirstName} {s.LastName}"))
                                    </div>
                                    <div class="col mt-1">
                                        <span><b>Актёры:</b></span>
                                        @string.Join(", ", movie.Actors.Select(a => $"{a.FirstName} {a.LastName}"))
                                    </div>
                                    <div class="col mt-1">
                                        <span><b>Качество:</b></span>
                                        .mp4
                                    </div>
                                </div>
                            </div>
                        </div>
                        if (!movie.Equals(Model.MoviesPage.Items.Last()))
                        {
                            <hr />
                        }
                    }
                    <div class="d-flex justify-content-center mt-3">
                        <div class="mx-2">
                            @if (Model.MoviesPage.CurrentPage > 1)
                            {
                                <a class="btn btn-primary btn-block text-truncate" href="@Url.Action("MovieIndex",
                                                                                                      new { page = Model.MoviesPage.CurrentPage - 1,
                                                                                                            search = Model.Search,
                                                                                                            sort = Model.Sort,
                                                                                                            titleFilter = Model.TitleFilter,
                                                                                                            directorFilter = Model.DirectorFilter,
                                                                                                            genreFilter = Model.GenreFilter })">
                                    <span class="glyphicon glyphicon-chevron-left"></span> назад
                                </a>
                            }
                            else
                            {
                                <a class="btn btn-primary disabled btn-block text-truncate">
                                    <span class="glyphicon glyphicon-chevron-left"></span> назад
                                </a>
                            }
                        </div>

                        <div class="mx-2">
                            @if (Model.MoviesPage.CurrentPage < Model.MoviesPage.TotalPages)
                            {
                                <a class="btn btn-primary btn-block text-truncate" href="@Url.Action("MovieIndex",
                                                                                                     new { page = Model.MoviesPage.CurrentPage - 1,
                                                                                                           search = Model.Search,
                                                                                                           sort = Model.Sort,
                                                                                                           titleFilter = Model.TitleFilter,
                                                                                                           directorFilter = Model.DirectorFilter,
                                                                                                           genreFilter = Model.GenreFilter })">
                                    далее <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            }
                            else
                            {
                                <a class="btn btn-primary disabled btn-block text-truncate">
                                    далее <span class="glyphicon glyphicon-chevron-right"></span>
                                </a>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<button id="scroll-to-top-btn" class="btn btn-primary btn-floating"><i class="bi bi-arrow-up-circle"></i></button>