Cinema/Cinema.WEB/Controllers/GenreController.cs
using AutoMapper;
using Cinema.WEB.Helpers;
using Cinema.WEB.Models.GenreModels.GenreDtos;
using Cinema.WEB.Models.GenreModels.GenreVms;
using Cinema.WEB.Services.IServices;
using Microsoft.AspNetCore.Mvc;

namespace Cinema.WEB.Controllers
{
    public class GenreController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public GenreController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        // GET: GenreController
        public async Task<IActionResult> GenreIndex()
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var genreDtos = await _unitOfWork.Genres.GetAllGenersAsync(token!);
            var genreVms = _mapper.Map<List<GenreVm>>(genreDtos);
            if (genreDtos.Any())
            {
                return View(genreVms);
            }

            return View(genreVms);
        }

        // GET: GenreController/Create
        public ActionResult GenreCreate()
        {
            return View();
        }

        // POST: GenreController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GenreCreate(GenreCreateVM genreVm)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var genreDto = _mapper.Map<GenreCreateDto>(genreVm);
                var isSuccess = await _unitOfWork.Genres.CreateGenreAsync(genreDto, token!);
                if (isSuccess)
                {
                    TempData["success"] = "Жанр успешно добавлен!";
                    return RedirectToAction(nameof(GenreIndex));
                }
            }

            TempData["error"] = "Oops! Неудалось добавить жанр.";
            return View(genreVm);
        }

        // GET: GenreController/Edit
        public async Task<IActionResult> GenreUpdate(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var genreDto = await _unitOfWork.Genres.GetGenreAsync(id, token!);

            if (genreDto != null)
            {
                var genreVm = _mapper.Map<GenreVm>(genreDto);
                return View(genreVm);
            }

            return RedirectToAction(nameof(GenreIndex));
        }

        // POST: GenreController/Edit
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> GenreUpdate(GenreVm genreVm)
        {
            if (ModelState.IsValid)
            {
                var token = HttpContext.Session.GetString(SD.SessionToken);
                var genreDto = _mapper.Map<GenreDto>(genreVm);
                var isSuccess = await _unitOfWork.Genres.UpdateGenreAsync(genreDto, token!);
                if (isSuccess)
                {
                    TempData["success"] = "Жанр успешно обновлён!";
                    return RedirectToAction(nameof(GenreIndex));
                }
            }

            TempData["error"] = "Oops! Неудалось обновить жанр.";
            return View(genreVm);
        }

        // POST: GenreController/GenreDelete/5
        public async Task<IActionResult> GenreDelete(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var genreToDelete = await _unitOfWork.Genres.GetGenreAsync(id, token!);

            if (genreToDelete is not null)
            {
                var isSuccess = await _unitOfWork.Genres.DeleteGenreAsync(genreToDelete.Id, token!);
                if (isSuccess)
                {
                    TempData["success"] = "Жанр успешно удален!";
                    return RedirectToAction(nameof(GenreIndex));
                }
            }

            TempData["error"] = "Oops! Неудалось удалить жанр.";
            return RedirectToAction(nameof(GenreIndex));
        }
    }
}

Cinema/Cinema.WEB/Controllers/MovieController.cs
using AutoMapper;
using Cinema.WEB.Helpers;
using Cinema.WEB.Models.MovieModels.MovieVms;
using Cinema.WEB.Models.MovieModels;
using Microsoft.AspNetCore.Mvc;
using Cinema.WEB.Services.IServices;
using Cinema.WEB.Models.MovieModels.MovieDtos;

namespace Cinema.WEB.Controllers
{
    public class MovieController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;

        public MovieController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
        }

        //GET: MovieController/MovieIndex
        public async Task<IActionResult> MovieIndex(
            bool sort,
            string? titleFilter = null,
            string? genreFilter = null,
            string? directorFilter = null,
            string? search = null,
            int page = 1, int pageSize = 20)
        {
            var request = new MoviesFilterRequest(search, titleFilter, directorFilter, genreFilter, sort, pageSize, page);
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var pageResponse = await _unitOfWork.Movies.GetAllMoviesAsync(token!, request);
            if (pageResponse is not null)
            {
                return View(pageResponse);
            }

            return View(new MovieFilteredResponse());
        }

        //GET: MovieController/MovieDetails/5
        public async Task<IActionResult> MovieDetails(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var movieDto = await _unitOfWork.Movies.GetMovieAsync(id, token!);
            if (movieDto is null)
            {
                TempData["error"] = "Oops! Неудалось найти фильм.";
                return RedirectToAction(nameof(MovieIndex));
            }

            var movieVm = _mapper.Map<MovieVm>(movieDto);   
            return View(movieVm);
        }

        //GET: MovieController/MovieCreate
        public async Task<IActionResult> MovieCreate()
        {
            var movieVm = new MovieCreateVm();
            var token = HttpContext.Session.GetString(SD.SessionToken);
            movieVm.ActorList = await _unitOfWork.Actors.GetSelectListOfActorsAsync(token!, movieVm.Movie.Actors);
            movieVm.DirectorList = await _unitOfWork.Directors.GetSelectListOfDirectorsAsync(token!, movieVm.Movie.Directors);
            movieVm.ScreenwriterList = await _unitOfWork.Screenwriters.GetSelectListOfScreenwritersAsync(
                token!, movieVm.Movie.Screenwriters);
            movieVm.GenreList = await _unitOfWork.Genres.GetSelectListOfGenresAsync(token!);
            return View(movieVm);
        }

        // POST: MovieController/MovieCreate
        [HttpPost]
        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]  
        public async Task<IActionResult> MovieCreate(MovieCreateVm movieVm)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            if (ModelState.IsValid)
            {
                movieVm.Movie.ImageUrl = await _unitOfWork.Images.SaveImageAsync(movieVm.ImageFile, movieVm.Movie.ImageUrl, @"images\movies");
                movieVm.Movie.VideoUrl = await _unitOfWork.Videos.SaveVideoAsync(movieVm.VideoFile, movieVm.Movie.VideoUrl, @"videos\movies");
                var response = await _unitOfWork.Movies.CreateMovieAsync(movieVm.Movie, token!);
                if (response.IsSuccess)
                {
                    TempData["success"] = "Информация успешно добавлена!";
                    return RedirectToAction(nameof(MovieIndex));
                }

                _unitOfWork.Images.DeleteImage(movieVm.Movie.ImageUrl);
                _unitOfWork.Videos.DeleteVideo(movieVm.Movie.VideoUrl);
                movieVm.Movie.ImageUrl = null;
                movieVm.Movie.VideoUrl = null;
                movieVm.ActorList = await _unitOfWork.Actors.GetSelectListOfActorsAsync(token!, movieVm.Movie.Actors);
                movieVm.DirectorList = await _unitOfWork.Directors.GetSelectListOfDirectorsAsync(token!, movieVm.Movie.Directors);
                movieVm.ScreenwriterList = await _unitOfWork.Screenwriters.GetSelectListOfScreenwritersAsync(
                    token!, movieVm.Movie.Screenwriters);
                movieVm.GenreList = await _unitOfWork.Genres.GetSelectListOfGenresAsync(token!);
                if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    TempData["error"] = string.Join("\n", response.ErrorMessage);
                    return View(movieVm);
                }
            }

            TempData["error"] = "Oops! Не удалось добавить информацию.";
            return View(movieVm);
        }

        //GET: MovieController/MovieUpdate/1
        public async Task<IActionResult> MovieUpdate(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var movieDto = await _unitOfWork.Movies.GetMovieAsync(id, token!);
            var movieVm = new MovieUpdateVm
            {
                Movie = _mapper.Map<MovieUpdateDto>(movieDto)
            };

            if (movieVm.Movie is null)
            {
                return RedirectToAction(nameof(MovieIndex));
            }

            movieVm.ActorList = await _unitOfWork.Actors.GetSelectListOfActorsAsync(token!, movieVm.Movie.Actors);
            movieVm.DirectorList = await _unitOfWork.Directors.GetSelectListOfDirectorsAsync(token!, movieVm.Movie.Directors);
            movieVm.ScreenwriterList = await _unitOfWork.Screenwriters.GetSelectListOfScreenwritersAsync(
                token!, movieVm.Movie.Screenwriters);
            movieVm.GenreList = await _unitOfWork.Genres.GetSelectListOfGenresAsync(token!);
            return View(movieVm);
        }

        [HttpPost]
        [DisableRequestSizeLimit]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> MovieUpdate(MovieUpdateVm movieVm)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            if (ModelState.IsValid)
            {
                var oldImgPath = movieVm.Movie.ImageUrl;
                var oldVideoPath = movieVm.Movie.VideoUrl;
                movieVm.Movie.ImageUrl = await _unitOfWork.Images.SaveImageAsync(movieVm.ImageFile, movieVm.Movie.ImageUrl, @"images\movies");
                movieVm.Movie.VideoUrl = await _unitOfWork.Videos.SaveVideoAsync(movieVm.VideoFile, movieVm.Movie.VideoUrl, @"videos\movies");
                var response = await _unitOfWork.Movies.UpdateMovieAsync(movieVm.Movie, token!);
                if (response.IsSuccess)
                {
                    TempData["success"] = "Информация успешно обновлена!";
                    _unitOfWork.Images.DeleteImage(oldImgPath);
                    _unitOfWork.Videos.DeleteVideo(oldVideoPath);
                    return RedirectToAction(nameof(MovieIndex));
                }

                _unitOfWork.Images.DeleteImage(movieVm.Movie.ImageUrl);
                _unitOfWork.Videos.DeleteVideo(movieVm.Movie.VideoUrl);
                movieVm.Movie.ImageUrl = oldImgPath;
                movieVm.Movie.VideoUrl = oldVideoPath;
                movieVm.ActorList = await _unitOfWork.Actors.GetSelectListOfActorsAsync(token!, movieVm.Movie.Actors);
                movieVm.DirectorList = await _unitOfWork.Directors.GetSelectListOfDirectorsAsync(token!, movieVm.Movie.Directors);
                movieVm.ScreenwriterList = await _unitOfWork.Screenwriters.GetSelectListOfScreenwritersAsync(token!, movieVm.Movie.Screenwriters);
                movieVm.GenreList = await _unitOfWork.Genres.GetSelectListOfGenresAsync(token!);
                if (response.StatusCode == System.Net.HttpStatusCode.BadRequest)
                {
                    TempData["error"] = string.Join("\n", response.ErrorMessage);
                    return View(movieVm);
                }
            }

            TempData["error"] = "Oops! Не удалось обновить информацию.";
            return View(movieVm);
        }

        //POST: MovieController/MovieDelete
        public async Task<IActionResult> MovieDelete(Guid id)
        {
            var token = HttpContext.Session.GetString(SD.SessionToken);
            var movieToDelete = await _unitOfWork.Movies.GetMovieAsync(id, token!);
            if (movieToDelete is not null)
            {
                var isSuccess = await _unitOfWork.Movies.DeleteMovieAsync(id, token!);
                if (isSuccess)
                {
                    if (movieToDelete.ImageUrl is not null)
                        _unitOfWork.Images.DeleteImage(movieToDelete.ImageUrl);
                    if (movieToDelete.VideoUrl is not null)
                        _unitOfWork.Videos.DeleteVideo(movieToDelete?.VideoUrl);
                    TempData["success"] = "Информация успешно удалена!";
                    return RedirectToAction(nameof(MovieIndex));
                }
            }

            TempData["error"] = "Oops! Не удалось удалить информация.";
            return RedirectToAction(nameof(MovieIndex));
        }
    }
}

Cinema/Cinema.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cinema.WEB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
     <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Cinema.WEB.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Cinema.WEB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="GenreIndex">Жанры</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Person" asp-action="PersonIndex">Касты</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="MovieIndex">Фильмы</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cinema.WEB - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.tiny.cloud/1/n94ifuzvl80pchikopiwgz2esrw8n28dwcywvpejlqrregfp/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/scrollToTop.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Cinema/Cinema.WEB/Views/Shared/_MultipleSelectionPartial.cshtml
<script>
    $(document).ready(function () {
        $("#Movie_Actors, #Movie_Directors, #Movie_Screenwriters").on("mousedown", function (e) {
            e.preventDefault();
            $(this).focus();
            var scroll = this.scrollTop;
            e.target.selected = !e.target.selected;
            this.scrollTop = scroll;
            $(this).trigger("change");
        });
    });
</script>

Cinema/Cinema.WEB/Views/Shared/_Notification.cshtml
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'center',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 5000,
            timerProgressBar: true
        })
    </script>
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'center',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 5000,
            timerProgressBar: true
        })
    </script>
}

Cinema/Cinema.WEB/Views/Shared/_PreviewImagePartial.cshtml
<script>
    function previewImage() {
        var preview = document.getElementById("preview");
        var fileInput = document.getElementById('fileInput');
        var file = fileInput.files[0];
        var reader = new FileReader();
        reader.onloadend = function () {
            preview.src = reader.result;
        }
        if (file) {
            reader.readAsDataURL(file);
        } else {
            preview.src = "";
        }
    }
</script>

Cinema/Cinema.WEB/Views/Shared/_SaveMessagePartial.cshtml
<script>
    const submitButton = document.querySelector('#submitButton');
    const form = document.querySelector('#myForm');

    submitButton.addEventListener('click', (event) => {
        event.preventDefault();
        Swal.fire({
            title: "Сохранение...",
            text: "Пожалуйста, подождите",
            showConfirmButton: false,
            allowEscapeKey: false,
            allowOutsideClick: false,
            didOpen: () => {
                Swal.showLoading();
            }
        });

        setTimeout(() => {
            form.submit();
        }, 5000);
    });
</script>

Cinema/Cinema.WEB/Views/Shared/_TextareaScriptPartial.cshtml
<script>
    tinymce.init({
        selector: 'textarea',
        plugins: 'advlist autolink lists link image charmap print preview hr anchor pagebreak',
        toolbar_mode: 'floating',
    });
</script>